const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const outputPath = path.join(__dirname, 'env-config.js');

// Read from .env file first, then supplement with process.env (for Vercel deployment)
const rawVars = {};

// 1. Parse .env file if it exists
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf-8');
  const lines = envContent.split('\n');
  lines.forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) return;
    const key = trimmed.slice(0, eqIdx).trim();
    let value = trimmed.slice(eqIdx + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    if (value && value !== 'REPLACE_WITH_YOUR_KEY') {
      rawVars[key] = value;
    }
  });
  console.log('Read ' + Object.keys(rawVars).length + ' vars from .env');
}

// 2. Supplement with process.env (for Vercel deployment)
const FRONTEND_KEYS = [
  'OPENAI_API_KEY',
  'ANTHROPIC_API_KEY',
  'GOOGLE_AI_API_KEY',
  'GROQ_API_KEY',
  'DEEPSEEK_API_KEY',
  'MISTRAL_API_KEY',
  'COHERE_API_KEY',
  'TOGETHER_API_KEY',
  'HUGGINGFACE_API_KEY',
  'FIREWORKS_API_KEY',
  'OPENROUTER_API_KEY',
  'REPLICATE_API_KEY',
  'HPC_API_KEY',
  'TAVILY_API_KEY',
  'SERPER_API_KEY',
  'BRAVE_SEARCH_API_KEY',
  'SERP_API_KEY',
  'SCRAPER_API_KEY',
  'ZENROWS_API_KEY',
  'SCRAPINGBEE_API_KEY',
  'CRAWLBASE_API_KEY',
  'WEBSCRAPING_AI_KEY',
  'ALIEXPRESS_API_KEY',
  'ALIEXPRESS_APP_KEY',
  'CJ_API_KEY',
  'RAINFOREST_API_KEY',
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
  'BACKEND_URL',
  'TRENDARYO_API_URL',
  'TRENDARYO_STORE_URL',
];

FRONTEND_KEYS.forEach((key) => {
  if (!rawVars[key] && process.env[key]) {
    rawVars[key] = process.env[key];
  }
});

// Only include frontend-safe keys (NOT backend secrets)
const vars = {};
FRONTEND_KEYS.forEach((key) => {
  if (rawVars[key]) vars[key] = rawVars[key];
});

// Map .env keys to app provider names
const aiKeyMap = {
  OPENAI_API_KEY: 'openai',
  ANTHROPIC_API_KEY: 'anthropic',
  GOOGLE_AI_API_KEY: 'google',
  GROQ_API_KEY: 'groq',
  DEEPSEEK_API_KEY: 'deepseek',
  MISTRAL_API_KEY: 'mistral',
  COHERE_API_KEY: 'cohere',
  TOGETHER_API_KEY: 'together',
  HUGGINGFACE_API_KEY: 'huggingface',
  FIREWORKS_API_KEY: 'fireworks',
  OPENROUTER_API_KEY: 'openrouter',
  REPLICATE_API_KEY: 'replicate',
};

const webSearchKeyMap = {
  TAVILY_API_KEY: 'tavily',
  BRAVE_SEARCH_API_KEY: 'brave',
  SERP_API_KEY: 'serpapi',
};

const platformKeyMap = {
  ALIEXPRESS_API_KEY: 'aliexpress',
  CJ_API_KEY: 'cjdropshipping',
  RAINFOREST_API_KEY: 'amazon',
};

const backendUrl = vars.BACKEND_URL || vars.TRENDARYO_API_URL || '';

const js = [
  '(function() {',
  '  // AUTO-GENERATED by build-env.cjs — DO NOT EDIT',
  '  // Source: .env — Generated: ' + new Date().toISOString(),
  '  // NOTE: Only frontend-safe keys are included. Backend secrets are excluded.',
  '',
  '  var HD = window.HuntDrop = window.HuntDrop || {};',
  '  HD._proxyUrl = ' + JSON.stringify(backendUrl ? backendUrl.replace(/\/?$/, '') + '/api/platform' : '') + ';',
  '  HD._envLoaded = true;',
  '',
  '  var ALL_ENV = ' + JSON.stringify(vars) + ';',
  '  var AI_KEY_MAP = ' + JSON.stringify(aiKeyMap) + ';',
  '  var WEB_KEY_MAP = ' + JSON.stringify(webSearchKeyMap) + ';',
  '  var PLAT_KEY_MAP = ' + JSON.stringify(platformKeyMap) + ';',
  '',
  '  // Store raw env keys globally so plugins can read them even if Config is not ready yet',
  '  HD._envKeys = {};',
  '  Object.keys(AI_KEY_MAP).forEach(function(envKey) {',
  '    var val = ALL_ENV[envKey];',
  '    if (val) HD._envKeys[AI_KEY_MAP[envKey]] = val;',
  '  });',
  '',
  '  var _envConfigAttempts = 0;',
  '  function initEnvConfig() {',
  '    _envConfigAttempts++;',
  '    try {',
  '      var Config = window.HuntDrop && window.HuntDrop.Config;',
  '      if (!Config) {',
  '        if (_envConfigAttempts < 20) {',
  '          setTimeout(initEnvConfig, 50);',
  '        }',
  '        return;',
  '      }',
  '',
  '      // --- AI Provider Keys ---',
  '      var aiKeysConfig = Config.get("aiKeys.keys") || {};',
  '      var foundAI = [];',
  '      var defaultProvider = "groq";',
  '',
  '      Object.keys(AI_KEY_MAP).forEach(function(envKey) {',
  '        var value = ALL_ENV[envKey];',
  '        if (!value) return;',
  '        var provider = AI_KEY_MAP[envKey];',
  '        if (!aiKeysConfig[provider]) {',
  '          aiKeysConfig[provider] = "plain:" + value;',
  '          foundAI.push(provider);',
  '        }',
  '      });',
  '',
  '      if (foundAI.indexOf("groq") !== -1) defaultProvider = "groq";',
  '      else if (foundAI.length > 0) defaultProvider = foundAI[0];',
  '',
  '      Config.set("aiKeys.keys", aiKeysConfig);',
  '      Config.set("aiKeys.provider", Config.get("aiKeys.provider") || defaultProvider);',
  '      Config.set("aiKeys.model", Config.get("aiKeys.model") || "llama3-70b-8192");',
  '',
  '      // --- Web Search Keys ---',
  '      Object.keys(WEB_KEY_MAP).forEach(function(envKey) {',
  '        var value = ALL_ENV[envKey];',
  '        var provider = WEB_KEY_MAP[envKey];',
  '        if (value && !Config.get("webSearch.key")) {',
  '          Config.set("webSearch.provider", provider);',
  '          Config.set("webSearch.key", value);',
  '        }',
  '      });',
  '',
  '      // --- Platform Keys (localStorage for frontend) ---',
  '      Object.keys(PLAT_KEY_MAP).forEach(function(envKey) {',
  '        var value = ALL_ENV[envKey];',
  '        var platform = PLAT_KEY_MAP[envKey];',
  '        if (!value) return;',
  '        var storageKey = "huntdrop_platform_" + platform + "_key";',
  '        try {',
  '          if (!localStorage.getItem(storageKey)) {',
  '            localStorage.setItem(storageKey, btoa(unescape(encodeURIComponent(value))));',
  '          }',
  '        } catch(e) { /* quota */ }',
  '      });',
  '',
  '      HD._envLoaded = true;',
  '      console.log("[EnvConfig] Loaded " + foundAI.length + " AI keys, web search: " + (Config.get("webSearch.key") ? "yes" : "no") + ", platforms: " + Object.keys(PLAT_KEY_MAP).length);',
  '    } catch(e) {',
  '      console.warn("[EnvConfig] Error:", e);',
  '    }',
  '  }',
  '',
  '  // Start polling for Config availability immediately, then retry every 50ms',
  '  initEnvConfig();',
  '})();',
].join('\n');

fs.writeFileSync(outputPath, js, 'utf-8');
console.log('env-config.js generated with ' + Object.keys(vars).length + ' frontend-safe variables');
